import { Item } from './components/ItemCard';

export const mockItems: Item[] = [
  {
    id: '1',
    type: 'lost',
    title: 'Apple AirPods Pro',
    category: 'Electronics',
    location: 'Main Library, 2nd Floor',
    date: '2025-01-14',
    status: 'posted',
    description: 'Lost my white AirPods Pro in the library. Black case with a small scratch on the lid. Left side bud has a green sticker.',
    postedBy: 'Nakul T.',
  },
  {
    id: '2',
    type: 'found',
    title: 'Bennett University ID Card',
    category: 'ID/Cards',
    location: 'Cafeteria Block C',
    date: '2025-01-13',
    status: 'matched',
    description: 'Found a student ID card near the cafeteria entrance. Name visible on the card. Please claim with proof.',
    postedBy: 'Samarpit M.',
  },
  {
    id: '3',
    type: 'lost',
    title: 'Blue Leather Wallet',
    category: 'Accessories',
    location: 'Sports Complex',
    date: '2025-01-12',
    status: 'claimed',
    description: 'Lost a blue leather bi-fold wallet near the basketball court. Contains some cash and a debit card.',
    postedBy: 'Tanishq M.',
  },
  {
    id: '4',
    type: 'found',
    title: 'MacBook Charger (MagSafe)',
    category: 'Electronics',
    location: 'Computer Lab 101',
    date: '2025-01-15',
    status: 'posted',
    description: 'Found a MagSafe charger left in computer lab 101 after the 3pm batch. 140W USB-C model.',
    postedBy: 'Priya S.',
  },
  {
    id: '5',
    type: 'lost',
    title: 'Prescription Glasses',
    category: 'Accessories',
    location: 'Lecture Hall B2',
    date: '2025-01-11',
    status: 'resolved',
    description: 'Lost black-rimmed prescription glasses (-2.5 power) in a grey case, possibly left under desk in B2.',
    postedBy: 'Arjun K.',
  },
  {
    id: '6',
    type: 'found',
    title: 'Notebook & Pen Set',
    category: 'Stationery',
    location: 'Hostel Block A',
    date: '2025-01-14',
    status: 'posted',
    description: 'Found a spiral notebook with a pen set near the hostel A common room. Name written inside cover.',
    postedBy: 'Riya D.',
  },
  {
    id: '7',
    type: 'lost',
    title: 'Keys Bunch (3 keys + fob)',
    category: 'Keys',
    location: 'Parking Area',
    date: '2025-01-10',
    status: 'matched',
    description: 'Lost a bunch of 3 keys with a red rubber fob near the two-wheeler parking. One key has "Honda" engraved.',
    postedBy: 'Dev P.',
  },
  {
    id: '8',
    type: 'found',
    title: 'Grey Hoodie',
    category: 'Clothing',
    location: 'Gym',
    date: '2025-01-13',
    status: 'posted',
    description: 'Found a grey hoodie (L size) left in the gym changing room. Has a small Bennett emblem on the left chest.',
    postedBy: 'Meera J.',
  },
];

export const mockNotifications = [
  { id: 'n1', message: 'Your lost item "AirPods Pro" has a potential match!', time: '2 min ago', read: false, type: 'match' },
  { id: 'n2', message: 'Claim for "Blue Leather Wallet" was approved.', time: '1 hr ago', read: false, type: 'claim' },
  { id: 'n3', message: 'New found item posted in Library — may match your report.', time: '3 hr ago', read: true, type: 'info' },
  { id: 'n4', message: 'Reminder: Update status for "MacBook Charger" post.', time: '1 day ago', read: true, type: 'reminder' },
];

export const stats = {
  totalItems: 143,
  resolvedThisMonth: 38,
  pendingClaims: 12,
  activeUsers: 274,
};
